### PR TITLE
Adds who approved/rejected request to app logs + log it in the Access…

### PR DESCRIPTION
**Pull request by SMxJrz**
These changes log who approved/rejected a Gatekeeper Access Request #14

### CODE REVIEW

**Comment by SMxJrz** [comment]
Right now it won't log who canceled it. Only when a request is Approved/Rejected, the user gets logged. Is that something we want to do?

**Comment by kood1** [comment]
If it’s not hard, we may want to record all actions for full audit trail as well as be consistent.

**Comment by SMxJrz** [comment]
It shouldn't be that hard to add but I probably need to rename the 2 columns I introduced on each side since it could be just the person making the request canceling it (who is not going to be an approver)

**Comment by kood1** [comment]
Let’s leave it out for now since the important part is approve/reject log for audit trail.

**Comment by SMxJrz** [comment]
Ehhh, I'm just going to go through with it now. Better to get it in now than worry about it later

**Comment by SMxJrz** [comment]
Merging

**Pull request merged**
